// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 10.1.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2021-05-01 12:05:54

// !!! ATTENTION !!!
// This is an auto-generated file with form declaration and initialization.
// Include it into your form class header file and derive your form from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// For example:
//     Form1.h:
//         #include "IForm1.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace app
//             {
//                 class CForm1 : public IForm1 // Derive your form from class from this file
//                 {
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     CForm1(); // Declare constructor
//                 };
//             }
//         }
//
//     Form1.cpp:
//         #include "Standard/Platform/Windows/Window.h" // Include required platform window management class
//         #include "Standard/Platform/Windows/OpenGL/Renderer.h" // Include required renderer
//         #include "Form1.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace app
//             {
//                 CForm1::CForm1(): // Implement constructor of your form
//                     IForm1(new standard::windows::CWindow(), new standard::windows::opengl::CRenderer(false, 0))
//                 {
//                     // Insert your code here
//                 }
//
//                 void CForm1::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//             }
//         }


#pragma once

#include "Nitisa/Core/Form.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/IFormService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "Standard/Controls/BitBtn/BitBtn.h"
#include "Standard/Controls/Edit/Edit.h"

namespace nitisa
{
	class IRenderer;
	class IWindow;
	struct CreateParams;

	namespace app
	{
		class IForm1 : public CForm
		{
		protected:
			// Controls
			standard::CBitBtn *m_pBitBtn1;
			standard::CEdit *m_pEdit1;

		private:
			void Initialize()
			{
				// Create controls
				m_pBitBtn1 = new standard::CBitBtn(this);
				m_pBitBtn1->setName(L"BitBtn1");
				m_pEdit1 = new standard::CEdit(this);
				m_pEdit1->setName(L"Edit1");

				// Initialize controls
				m_pBitBtn1->setName(UTF8ToString("BitBtn1"));
				m_pBitBtn1->getTransform()->Translate(180.0f, 450.0f, 0.0f);
				m_pBitBtn1->setTabOrder(1);
				m_pBitBtn1->setCaption(UTF8ToString("Ok"));

				m_pEdit1->setName(UTF8ToString("Edit1"));
				m_pEdit1->getTransform()->Translate(170.0f, 410.0f, 0.0f);
				m_pEdit1->setSize(PointF{ 660.0f, 31.0f });
				m_pEdit1->setTabOrder(2);
				m_pEdit1->setText(UTF8ToString("Edit1"));


			}

		public:
			IForm1(IWindow *window, IRenderer *renderer, const String &class_name = L"Form1", const CreateParams *params = nullptr) :
				CForm(class_name, nullptr, renderer, params),
				m_pBitBtn1{ nullptr },
				m_pEdit1{ nullptr }
			{
				if (window)
				{
					CLockRepaint lock(this);
					setClientSize(Point{ 854, 480 });
					QueryService()->setWindow(window);
					Application->QueryService()->Add(this);
					Initialize();
				}
			}
		};
	}
}
